package home.work.project2;

public class Exception {

	public static void main(String[] args) {
		
		try {
			
		
		int a= 40/0;
		}
		
		catch (ArithmeticException e) {
		
			System.out.println("print1");
		}
		System.out.println("Print");
	}

	
}
